/**
 * Sidebar configuration using autogenerated content
 * The sorting of items (folders first, then files) is handled by the theme component
 */
export default {
  docs: [
    {
      type: 'autogenerated',
      dirName: '.', // '.' means the entire docs folder
    },
  ],
};
